# available template place holders:
# ${base-branch}
# ${base-version}
# ${head-branch}
# ${head-version}
# ${is-prerelease}
# ${is-draft-pr}
pull-request:
  title: New images avaialbe in Azure Marketplace
  description: >-
    This pull request is automatically created because new FOS / FAZ versions are detected in the Azure Marketplace.
    QA process is required before integrating these versions into our latest Autoscale Azure project.
  reviewers: # array of GitHub login
    - jamie-pate
    - Joel-Cripps
    - JaydenLiang
  team-reviewers: # array of GitHub login
  labels: # array of string literal
    - marketplace updates
