# available template place holders:
# ${base-branch}
# ${base-version}
# ${head-branch}
# ${head-version}
# ${is-prerelease}
# ${is-draft-pr}
pull-request:
  title: Bumping version to ${head-version}
  description: >-
    This pull request is automatically issued to bump version of branch: ${base-branch} to ${head-version} for a new release.
  assignees: # array of GitHub login
  reviewers: # array of GitHub login
    - jamie-pate
    - JaydenLiang
    - Joel-Cripps
  team-reviewers: # array of GitHub login
  labels: # array of string literal
    - version branch
    - release pipeline
